FROM node:22.16.0-slim

WORKDIR /app
RUN apt-get update && apt-get install -y build-essential python3 make
COPY package.json package-lock.json* ./
RUN npm install
RUN npm install lightningcss-linux-x64-gnu
COPY . .
EXPOSE 4000
CMD ["npm", "run", "dev" ]

