default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "1234") %>
  pool: 5

development:
  <<: *default
  database: dodo_library_db_development

test:
  <<: *default
  database: dodo_library_db_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
