source "https://rubygems.org"

gem "rails", "~> 8.0.2"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"
gem "bootsnap", require: false
gem "kamal", require: false
gem "thruster", require: false
gem "pg"
gem "graphql"
gem "bcrypt"
gem "kaminari"
gem "jwt"
gem "pundit"
gem 'rack-cors'
gem 'rails_12factor'


group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "graphiql-rails"
end

gem "rspec-rails", "~> 8.0", :group => :test
gem 'factory_bot_rails', :group => :test
gem 'faker', :group => :test
gem 'shoulda-matchers', :group => :test