default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 1234
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dodo_library_db_development

test:
  <<: *default
  database: dodo_library_db_test

production:
  <<: *default
  database: dodo_library_db_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %> # para segurança no production
